# fly.toml app configuration file generated for shine-app on 2023-06-18T11:55:29+02:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "shine-app"
primary_region = "cdg"

[http_service]
  internal_port = 80
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0

[metrics]
    port = 80
    path = "/identity/api/telemetry/metrics"
