[versions]
agp = "8.13.0"
androidx-appcompat = "1.7.1"
androidx-games-activity = "2.0.2" # cannot update, see: https://github.com/rust-mobile/android-activity/issues/210
androidx-browser = "1.9.0"
androidx-security = "1.1.0"
material = "1.13.0"
okhttp = "5.2.1"

junit = "4.13.2"
junitVersion = "1.3.0"
androidx-espresso-core = "3.7.0"
kotlin = "2.2.0"
coreKtx = "1.17.0"

[libraries]
junit = { group = "junit", name = "junit", version.ref = "junit" }
ext-junit = { group = "androidx.test.ext", name = "junit", version.ref = "junitVersion" }
androidx-espresso-core = { group = "androidx.test.espresso", name = "espresso-core", version.ref = "androidx-espresso-core" }

androidx-appcompat = { group = "androidx.appcompat", name = "appcompat", version.ref = "androidx-appcompat" }
androidx-games-activity = { group = "androidx.games", name = "games-activity", version.ref = "androidx-games-activity" }
androidx-browser = { group = "androidx.browser", name = "browser", version.ref = "androidx-browser" }
androidx-security = { group = "androidx.security", name = "security-crypto", version.ref = "androidx-security" }
material = { group = "com.google.android.material", name = "material", version.ref = "material" }
okhttp = { module = "com.squareup.okhttp3:okhttp", version.ref = "okhttp" }
androidx-core-ktx = { group = "androidx.core", name = "core-ktx", version.ref = "coreKtx" }

[plugins]
android-application = { id = "com.android.application", version.ref = "agp" }
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
